#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT=6379
CONF_FILE=redis
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli
PASSWORD=password
SHUTDOWN="f7c7d0ed0e1d9313a8192805bb6a8221539c95270ad90ed017d5110121c3c0371772724678526f7d9a897c22e8043fb197804232c3f0d00917416c20f9e7cead"

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/etc/redis/${CONF_FILE}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -a "$PASSWORD" -p $REDISPORT "$SHUTDOWN"
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
